#!/bin/bash

. /etc/hamonize/propertiesJob/propertiesInfo.hm

CENTERURL="http://${CENTERURL}/hmsvc/updtpolicy"
PCUUID=$(cat /etc/hamonize/uuid)

LOGFILE="/var/log/hamonize/agentjob/updp.log"
TENANT=$(cat /etc/hamonize/hamonize_tanent)

# 파일을 다운로드할 서버 URL 
FILESERVERURL="192.168.0.200:5000"
touch $LOGFILE

echo "################### updt deb install ###########################" >>$LOGFILE

UPDT_INS=$(cat /etc/hamonize/updt/updtInfo.hm | jq '.INS' | sed -e "s/\"//g")
SID=$(cat /etc/hamonize/updt/updtInfo.hm | jq '.SID' | sed -e "s/\"//g")

if [ "$UPDT_INS" != null ]; then
    echo "install file total  data=========$UPDT_INS" >>$LOGFILE

    # 입력받은 문자열을 쉼표(,)를 기준으로 분리하여 배열에 저장
    IFS=',' read -ra str_array <<<"$UPDT_INS"

    # 반복문을 이용하여 파일 다운로드 수행
    for str in "${str_array[@]}"; do
        echo "다운로드 중인 파일: $str" >>$LOGFILE

        # curl 명령어를 이용하여 파일 다운로드
        if curl -s -O "http://${FILESERVERURL}/webapi/entry.cgi?api=SYNO.FileStation.Download&version=2&method=download&_sid=${SID}&path=/hamonize/${TENANT}/${str}"; then
            echo "$str 다운로드가 완료되었습니다." >>$LOGFILE
            sudo dpkg -i ${str}

            # dpkg 명령어의 반환 코드를 확인하여 설치가 성공적으로 수행되었는지 확인
            if [[ $? -eq 0 ]]; then
                echo "$str 설치가 완료되었습니다." >>$LOGFILE
                mv ${str} /tmp/

                # package_name = `dpkg --info /tmp/htop_2.2.0-2build1_amd64.deb | grep Package | awk '{print $2}'`
                packageNm=$(dpkg --info /tmp/${str} | grep Package | awk '{print $2}')
                INS_FILE_PATH=$(which $packageNm)
                INS_CHK_CNT=$(dpkg --get-selections | grep $packageNm | grep -v "[[:graph:]]$packageNm\|$packageNm[[:graph:]]" | wc -l)
                INS_PKG_VER=$(apt-cache policy $packageNm | grep -E '설치|Installed' | awk '{print $2}')
                INSRET=$INSRET"{\"debname\":\"${packageNm}\",\"debver\":\"${INS_PKG_VER}\",\"state\":\"$INS_CHK_CNT\",\"path\":\"$INS_FILE_PATH\"}"

                # echo $INSRET

                rm /tmp/${str}

            else
                echo "$str 설치가 실패했습니다." >>$LOGFILE
            fi
        else
            echo "$str 다운로드가 실패했습니다." >>$LOGFILE
        fi
    done

    UPDT_INSTALL_JSON="{\
        \"insresert\":[$INSRET],\
        \"updtresert\": [],\
        \"delresert\": [],\
        \"domain\": \"$TENANT\",\
        \"uuid\": \"$PCUUID\"\
        
    }"

    echo "UPDT_INSTALL_JSON >>> $UPDT_INSTALL_JSON" >>$LOGFILE

    RETUPDT=$(curl -X POST -H 'User-Agent: HamoniKR OS' -H 'Content-Type: application/json' -f -s -d "$UPDT_INSTALL_JSON" $CENTERURL)
fi

UPDT_DEL=$(cat /etc/hamonize/updt/updtInfo.hm | jq '.DEL' | sed -e "s/\"//g" | tr -d '[:space:]')
echo "delete file total  data=========$UPDT_DEL" >>$LOGFILE

if [ "$UPDT_DEL" != null ]; then
    # systemctl stop auditd
    # echo " data delete ==$UPDT_DEL===" >>$LOGFILE

    EC=0
    DELRET=""
    OLD_IFS=$IFS
    IFS=,
    for I in $UPDT_DEL; do

        echo "delete deb name is ===> $I" >>$LOGFILE

        INIT_DELETED_CHK=$(dpkg --get-selections | grep $I | grep -v "[[:graph:]]$I\|$I[[:graph:]]" | wc -l)
        echo "INIT_DELETED_CHK==========>$INIT_DELETED_CHK" >>$LOGFILE

        if [ "$INIT_DELETED_CHK" -eq 1 ]; then
            # echo "[$I] Not Deleted "          #>>$LOGFILE
            sudo apt-get remove --purge $I -y >>$LOGFILE

            sleep 1

            # Audit Program Block Delete
            APP_PATH=$(which $I)
            chkRules=$(auditctl -l | grep -e "$APP_PATH")
            if [[ -n $chkRules ]]; then
                sed -i "/${str}/d" "$RULE_FILE"
            fi

        else
            echo "[$I] package Deleted  " >>$LOGFILE
        fi

        DEL_CHK_CNT=$(dpkg --get-selections | grep $I | grep -v "[[:graph:]]$I\|$I[[:graph:]]" | wc -l)
        echo "del chk wc -l is ==> $DEL_CHK_CNT" >>$LOGFILE

        DEL_PKG_VER=$(apt-cache policy $NAME | grep -E '설치|Installed' | awk '{print $2}')

        DELRET=$DELRET"{\"debname\":\"${I}\",\"debver\":\"${DEL_PKG_VER}\",\"state\":\"$DEL_CHK_CNT\",\"path\":\"\"}"

        if [ "$EC" -eq "$#" ]; then
            DELRET=$DELRET","
        fi

        EC=$(expr "$EC" + 1)
    done

    # auditd 규칙 파일 로드
    /sbin/auditctl -R $RULE_FILE

    # auditd 서비스 재시작
    systemctl restart auditd

    IFS=$OLD_IFS

    
    echo "################## updt json data ############################" >>$LOGFILE

    UPDT_DELETE_JSON="{\
        \"insresert\":[],\
        \"updtresert\": [],\
        \"delresert\": [$DELRET],\
        \"domain\": \"$TENANT\",\
        \"uuid\": \"$PCUUID\"\
    }"

    echo "UPDT_DELETE_JSON >>> $UPDT_DELETE_JSON" >> $LOGFILE

    RETUPDT=$(curl -X POST -H 'User-Agent: HamoniKR OS' -H 'Content-Type: application/json' -f -s -d "$UPDT_DELETE_JSON" $CENTERURL)
    echo $RETUPDT >>$LOGFILE

fi

# rm -fr /etc/hamonize/runupdt.deb 2>/dev/null
